# Volumes for persisted data.
volumes:
  data_sendy:

networks:
  polrev-sendy:

services:
  # Database: MySQL
  db_sendy:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./config/.dev.env
    volumes:
      - data_sendy:/var/lib/mysql
    networks:
      - polrev-sendy

  # WebApp: Apache2+PHP+Sendy
  sendy:
    depends_on:
      - db_sendy
    image: sendy:latest
    build:
      context: .
      # Uncomment to enabled XDEBUG build
      # target: debug
    env_file: ./config/.dev.env
    ports:
      - 8000:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.middlewares=test-compress"
      - "traefik.http.middlewares.test-compress.compress=true"
    volumes:
      - ./html:/var/www/html
    networks:
      - polrev-sendy

  # Traffic
  traefik:
    image: "traefik:v2.5.4"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesResolvers.le.acme.email=admin@political-revolution.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"

    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - polrev-sendy
